import type { TravelTimeModel } from './travel-time.model'

export const travelTimeFixtures = (): TravelTimeModel[] => [
  {
    id: 1,
    line: 1,
    new: 23,
    old: 31,
    start: 'République',
    end: 'Grand Quartier',
  },
  {
    id: 2,
    line: 1,
    new: 20,
    old: 24,
    start: 'ZA Saint-Sulpice',
    end: 'République',
  },
  {
    id: 3,
    line: 2,
    new: 15,
    old: 15,
    start: 'Trois Marches',
    end: 'République',
  },
  {
    id: 4,
    line: 2,
    new: 31,
    old: 35,
    start: 'Rigourdière',
    end: 'République',
  },
  {
    id: 5,
    line: 2,
    new: 25,
    old: 29,
    start: 'Bourgchevreuil',
    end: 'République',
  },
  {
    id: 6,
    line: 3,
    new: 20,
    old: 25,
    start: 'Uttenreuth',
    end: 'République',
  },
  {
    id: 7,
    line: 3,
    new: 22,
    old: 36,
    start: 'Rosa Parks',
    end: 'République',
  },
  {
    id: 8,
    line: 3,
    new: 17,
    old: 25,
    start: 'Chantepie Mairie',
    end: 'République',
  },
  {
    id: 9,
    line: 4,
    new: 20,
    old: 31,
    start: 'Aéroport',
    end: 'Gares',
  },

  {
    id: 10,
    line: 4,
    new: 30,
    old: 32,
    start: 'Coeur de Campus',
    end: 'Gares',
  },
]
