import type { TravelTimeModel } from './travel-time.model'

export const travelTimeFixtures = (): TravelTimeModel[] => [
  {
    line: 1,
    new: 15,
    old: 40,
    start: 'JF Kennedy',
    end: 'Brécé',
  },
  {
    line: 1,
    new: 8,
    old: 32,
    start: 'JF Kennedy',
    end: 'Brécé',
  },
  {
    line: 2,
    new: 5,
    old: 15,
    start: 'JF Kennedy',
    end: 'Brécé',
  },
  // More items, the data is probably fake
  {
    line: 1,
    new: 23,
    old: 31,
    start: 'Grand Quartier',
    end: 'République',
  },
  {
    line: 1,
    new: 20,
    old: 24,
    start: 'ZA Saint-Sulpice',
    end: 'République',
  },
  {
    line: 2,
    new: 15,
    old: 20,
    start: 'Trois Marches',
    end: 'République',
  },
  {
    line: 2,
    new: 31,
    old: 35,
    start: 'Rigourdière',
    end: 'République',
  },
  {
    line: 2,
    new: 25,
    old: 29,
    start: 'Bourgchevreuil',
    end: 'République',
  },
  {
    line: 3,
    new: 15,
    old: 40,
    start: 'Uttenreuth',
    end: 'République',
  },
  {
    line: 3,
    new: 15,
    old: 40,
    start: 'Rosa Park',
    end: 'République',
  },
  {
    line: 3,
    new: 15,
    old: 40,
    start: 'Mairie Chantepie',
    end: 'République',
  },
  {
    line: 4,
    new: 15,
    old: 40,
    start: 'Aire Libre',
    end: 'Gare',
  },
  {
    line: 4,
    new: 15,
    old: 40,
    start: 'Aéroport',
    end: 'Gare',
  },
]
